kind: pipeline
type: docker
name: build

steps:
  - name: go_test
    image: golang:1.21.6
    commands:
      - go test -v ./...

  - name: gosec
    image: securego/gosec
    commands:
      - gosec ./...

  - name: build
    image: golang:1.21.6
    commands:
      - make all

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GH_APIKEY
      files: dist/*
      checksum:
        - sha256
    when:
      event: tag

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CHAT_ID
    when:
      status: [ failure ]